export const products = [
  {
    name: "Banane",
    cost: (1.64).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Coppa Cacao",
    cost: (0.24).toFixed(2),
    duration: 3.5,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Mozzarella",
    cost: (0.69).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Passata Bottiglia",
    cost: (0.58).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Speck",
    cost: (1.69).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Uova",
    cost: (1.14).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Yogurt",
    cost: (0.22).toFixed(2),
    duration: 3.3,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Tortelloni",
    cost: (1.49).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pangoccioli",
    cost: (1.19).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Salame",
    cost: (1.79).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Patatine Fritte",
    cost: (0.99).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pesto",
    cost: (0.99).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Carne Trita",
    cost: (3.69).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Olive",
    cost: (0.49).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Panna Cucina",
    cost: (0.59).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Parmigiano",
    cost: (1.49).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Sofficini",
    cost: (0.89).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Tonno",
    cost: (1.89).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Wurstel",
    cost: (1.09).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Piadine",
    cost: (1.79).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Carta Igenica",
    cost: (1.69).toFixed(2),
    duration: 28,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Biscotti Frollini",
    cost: (1.65).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Ketchup",
    cost: (0.99).toFixed(2),
    duration: 21,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Maionese",
    cost: (0.99).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pancetta",
    cost: (1.19).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Panini Hamburger",
    cost: (0.78).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pasta Corta",
    cost: (0.39).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pasta Lunga",
    cost: (0.65).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Salsiccia",
    cost: (2.89).toFixed(2),
    duration: 21,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Fettine Lonza",
    cost: (2.29).toFixed(2),
    duration: 21,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "The",
    cost: (0.99).toFixed(2),
    duration: 21,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Mais",
    cost: (1.39).toFixed(2),
    duration: 21,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pecorino Romano",
    cost: (1.19).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Riso",
    cost: (1.79).toFixed(2),
    duration: 28,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Sale Fino",
    cost: (0.17).toFixed(2),
    duration: 28,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Sale Grosso",
    cost: (0.17).toFixed(2),
    duration: 28,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Sottilette",
    cost: (0.79).toFixed(2),
    duration: 28,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Zucchero",
    cost: (0.65).toFixed(2),
    duration: 28,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Carta Forno",
    cost: (1.79).toFixed(2),
    duration: 56,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Concentrato 🍅",
    cost: (0.55).toFixed(2),
    duration: 56,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Olio",
    cost: (3.49).toFixed(2),
    duration: 56,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Alluminio",
    cost: (1.99).toFixed(2),
    duration: 84,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pepe Nero",
    cost: (0.89).toFixed(2),
    duration: 168,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pane Grattugiato",
    cost: (0.59).toFixed(2),
    duration: 28,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Croissant",
    cost: (0.95).toFixed(2),
    duration: 7,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Pizza",
    cost: (1.89).toFixed(2),
    duration: 14,
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: [],
  },
  {
    name: "Birra Bavaria",
    cost: (0.85).toFixed(2),
    duration: "",
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: ["Bonus"],
  },
  {
    name: "Patatine 300g",
    cost: (0.89).toFixed(2),
    duration: "",
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: ["Bonus"],
  },
  {
    name: "Croccantini",
    cost: (0.35).toFixed(2),
    duration: "",
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: ["Bonus"],
  },
  {
    name: "Succo Frutta",
    cost: (0.99).toFixed(2),
    duration: "",
    logs: [],
    lastUpdated: new Date(Date.now()).toISOString(),
    tags: ["Bonus"],
  },
];
